# Generated by Django 4.2.13 on 2024-06-14 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_tags_recipe_tags'),
        ('users', '0006_user_is_subscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'recipe_user',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='recipes',
            field=models.ManyToManyField(through='users.RecipeUser', to='recipes.recipe'),
        ),
    ]
