# Generated by Django 4.2.13 on 2024-06-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='подписан'),
        ),
        migrations.AlterField(
            model_name='user',
            name='recipes_count',
            field=models.IntegerField(default=0, verbose_name='количество рецептов'),
        ),
    ]
