# Generated by Django 4.2.13 on 2024-06-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_options_alter_user_is_subscribed_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('subscriber', 'user')},
        ),
    ]
