# Generated by Django 4.2.13 on 2024-06-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_subscription_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
    ]
